runtime: nodejs
env: flex

service: notifications

beta_settings:
  cloud_sql_instances: minimum-backend:us-east4:minimum-ai

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.8
